version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: communications_api_postgres
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: project_db
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user123"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
